workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: star_expedition_codemagic
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        #This has all 20 keys from the dotenv.env file:
        - star_expedition_credentials
      vars:
        BUNDLE_ID: "com.starexpedition"
        DISTRIBUTION_TYPE: "app_store"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Setting up keychain to be used for codesigning with Codemagic's CLI keychain command
        script: |
          keychain initialize

      - name: Fetching signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

      - name: Adding certificates to the keychain
        script: |
          keychain add-certificates

      - name: Setting up code signing settings on Xcode
        script: |
          xcode-project use-profiles

      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Create dotenv.env file from Codemagic environment variables
        script: |
          mkdir -p assets
          touch assets/dotenv.env
          echo "EMAIL_ADDRESS=$EMAIL_ADDRESS" >> assets/dotenv.env
          echo "APP_PASS=$APP_PASS" >> assets/dotenv.env
          echo "OPTIONS_DSN=$OPTIONS_DSN" >> assets/dotenv.env
          echo "FIREBASE_API_KEY=$FIREBASE_API_KEY" >> assets/dotenv.env
          echo "FIREBASE_APP_ID=$FIREBASE_APP_ID" >> assets/dotenv.env
          echo "FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL" >> assets/dotenv.env
          echo "FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID" >> assets/dotenv.env
          echo "FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID" >> assets/dotenv.env
          echo "FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET" >> assets/dotenv.env
          echo "WEB_API_KEY=$WEB_API_KEY" >> assets/dotenv.env
          echo "WEB_AUTH_DOMAIN=$WEB_AUTH_DOMAIN" >> assets/dotenv.env
          echo "WEB_PROJECT_ID=$WEB_PROJECT_ID" >> assets/dotenv.env
          echo "WEB_STORAGE_BUCKET=$WEB_STORAGE_BUCKET" >> assets/dotenv.env
          echo "WEB_MESSAGING_SENDER_ID=$WEB_MESSAGING_SENDER_ID" >> assets/dotenv.env
          echo "WEB_APP_ID=$WEB_APP_ID" >> assets/dotenv.env
          echo "MY_SUPABASE_URL=$MY_SUPABASE_URL" >> assets/dotenv.env
          echo "MY_SUPABASE_SERVICE_KEY=$MY_SUPABASE_SERVICE_KEY" >> assets/dotenv.env
          echo "MY_TOKEN=$MY_TOKEN" >> assets/dotenv.env
          echo "PUBLIC_TOKEN=$PUBLIC_TOKEN" >> assets/dotenv.env
          echo "MY_SOURCE_MAP_PATH=$MY_SOURCE_MAP_PATH" >> assets/dotenv.env

      - name: Install pods
        script: |
          find . -name "Podfile" -maxdepth 2 -execdir pod install \;

      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - starexpedition.theapp@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups: []
        submit_to_app_store: false